### GENERAL SETTINGS ###

# Site settings
title: Cailin Carrier art
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://cailincarrier.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - BC, Canada
email: cailinsdrawings@gmail.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Cailin Carrier
    position: Artist
    text: Best in the world.


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "I don't smell too bad."

# prose.io config
prose:
  rooturl: '_projects'
  media: 'assets/img/projects'
  ignore:
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - Gemfile
    - Gemfile.lock
    - /css
    - /assets
    - /js

  metadata:
    _projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "project"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "img"
        field:
          element: "text"
          label: "Image"
          help: "Add an image."
          placeholder: "Thumbnail"
          alterable: true
      - name: "category"
        field:
          element: "select"
          label: "Add category"
          placeholder: "Choose category"
          options:
            - name: "Animals"
              value: "Animals"
            - name: "Paintings"
              value: "Paintings"
            - name: "Paramedic"
              value: "Paramedic"
            - name: "Portrait"
              value: "Portrait"
            - name: "Scenic"
              value: "Scenic"
            - name: "Tattoos"
              value: "Tattoos"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

